services:

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped

    ports:
      - "8200:8200"

    cap_add:
      - IPC_LOCK

    command: >
      vault server
      -dev
      -dev-root-token-id={root}
      -dev-listen-address=0.0.0.0:8200

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped

    ports:
      - "8081:80"
      - "8443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: